// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bcgvduudtlaquerhrgxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjZ3ZkdXVkdGxhcXVlcmhyZ3htIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMjM2MjgsImV4cCI6MjA1OTc5OTYyOH0.wocZ61LN8OuDCkWiXTKlnIXgRSe3BAQLz5ySJ8icZ8o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);